### ISSUE TITLE
No confidence index showing

### ISSUE THREAD

**Issue by jemiku** [ucsb-goard-lab/EstrousNet#5]
I've read, that the program is currently under maintenance, so I don't know whether this is a feature, which is disabled right now , but the confidence index is not showing. Instead there is an empty diagram (picture). I'm no computer expert, but I did follow all the steps described in the ReadMe. 
![Bild](https://github.com/user-attachments/assets/e4892d34-1294-40d7-a733-a7fd49eb2d95)

**Comment by NoraWolcott** [comment]
Hi,

The confidence index is one currently disabled feature, which we should have up and running by the end of the month. I will clarify this in the ReadMe, thanks!
